services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Catalyst\:
        resource: '../src/*'

    Symfony\Component\Console\Application:
        public: true